[package]
name = "blog-cli"
version.workspace = true
edition.workspace = true

[dependencies]
blog-client.workspace = true
blog-shared.workspace = true
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dirs = "6.0.0"
